### ISSUE TITLE
The frozen state end after server restart but still have blindness 

### ISSUE THREAD

**Issue by khaoniaomamuang** [BGHDDevelopment/Ultimate-Freeze#1]
Hello,
The plugin should not unfreeze the player when the server restart.

**Comment by BGHDDevelopment** [comment]
The frozen players are not stored in a config, there stored in the plugin, which when the server restarts removes them.
Without a recode I can't add that feature.

Also support and suggestions are done through our discord not issues.

https://bghddevelopment.com/discord
https://feedback.bghddevelopment.com

If you wish to recode the system yourself feel free.
